"""new fields in user model

Revision ID: 32e047481290
Revises: 7ff53363f02d
Create Date: 2019-12-12 23:48:53.255143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e047481290'
down_revision = '7ff53363f02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('customer', sa.Column('userpic', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'userpic')
    op.drop_column('customer', 'about_me')
    # ### end Alembic commands ###
