"""users table

Revision ID: 481b7098ec57
Revises: 0d58a58e66eb
Create Date: 2019-12-18 11:37:33.561756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '481b7098ec57'
down_revision = '0d58a58e66eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_orders_email', table_name='orders')
    op.drop_index('ix_orders_username', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_orders_username', 'orders', ['username'], unique=True)
    op.create_index('ix_orders_email', 'orders', ['email'], unique=True)
    op.drop_table('followers')
    # ### end Alembic commands ###
