"""new fields in user model

Revision ID: 5f7e77a5bcde
Revises: 32e047481290
Create Date: 2019-12-13 12:12:13.542595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f7e77a5bcde'
down_revision = '32e047481290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'userpic',
               existing_type=mysql.VARCHAR(length=180),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'userpic',
               existing_type=mysql.VARCHAR(length=180),
               nullable=True)
    # ### end Alembic commands ###
