"""users table

Revision ID: 96d85bb39741
Revises: 481b7098ec57
Create Date: 2019-12-18 12:34:53.018995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96d85bb39741'
down_revision = '481b7098ec57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.drop_constraint('followers_ibfk_1', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'customer', ['followed_id'], ['id'])
    op.drop_column('followers', 'id')
    op.drop_column('followers', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('followers', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_ibfk_1', 'followers', 'customer', ['customer_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
