"""users table

Revision ID: b9585fc07cf4
Revises: 5f7e77a5bcde
Create Date: 2019-12-14 16:30:54.247188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9585fc07cf4'
down_revision = '5f7e77a5bcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photos_email', table_name='photos')
    op.drop_index('ix_photos_username', table_name='photos')
    op.drop_table('photos')
    op.add_column('post', sa.Column('photo', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'photo')
    op.create_table('photos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_photos_username', 'photos', ['username'], unique=True)
    op.create_index('ix_photos_email', 'photos', ['email'], unique=True)
    # ### end Alembic commands ###
